import os
import logging
from typing import Optional
from fastapi import Header, HTTPException, Request
from pydantic import BaseModel


# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize clients
# xion_cli_client = XionCLIClient()
# try:
#     # Initialize the contract service but gracefully handle errors
#     xion_contract_service = XionContractService()
#     contract_service_available = True
# except Exception as e:
#     logger.warning(f"Failed to initialize XionContractService: {str(e)}")
#     logger.warning("Will fall back to CLI client for all operations")
#     contract_service_available = False

class BlockchainCredentials(BaseModel):
    user_address: str
    secure_token: str

# Commented out blockchain verification and deduction functions
# async def verify_blockchain_credentials(
#     request: Request,
#     x_user_address: str = Header(..., description="User's wallet address"),
#     x_secure_token: str = Header(..., description="Session token generated by the contract")
# ) -> BlockchainCredentials:
#     """Verifies blockchain credentials from XION"""
#     # Basic validation
#     if not x_user_address or not x_user_address.startswith("xion"):
#         raise HTTPException(status_code=401, detail="Invalid wallet address format")
    
#     # Updated for real token format (3 parts)
#     if not x_secure_token or len(x_secure_token.split(":")) < 3:
#         raise HTTPException(status_code=401, detail="Invalid token format")
    
#     # Create credentials object
#     credentials = BlockchainCredentials(
#         user_address=x_user_address,
#         secure_token=x_secure_token
#     )
    
#     # First try using the contract service (preferred method)
#     if contract_service_available:
#         try:
#             logger.info(f"Trying to verify using contract service for: {x_user_address}")
#             is_valid = await xion_contract_service.verify_user_token(x_user_address, x_secure_token)
            
#             if is_valid:
#                 logger.info(f"Contract service validated credentials for: {x_user_address}")
#                 return credentials
            
#             logger.warning(f"Contract service rejected credentials for: {x_user_address}")
#         except Exception as e:
#             logger.error(f"Error using contract service: {str(e)}")
    
#     # Fall back to CLI client if contract service failed or isn't available
#     try:
#         logger.info(f"Falling back to CLI verification for: {x_user_address}")
#         is_valid = await xion_cli_client.verify_user_token(x_user_address, x_secure_token)
        
#         if is_valid:
#             logger.info(f"CLI validated credentials for: {x_user_address}")
#             return credentials
        
#         logger.warning(f"CLI rejected credentials for: {x_user_address}")
#         # PRODUCTION TESTING: Accept anyway for testing
#         logger.warning("PRODUCTION TESTING: Accepting despite verification failure")
#         return credentials
        
#         # REAL PRODUCTION: Use this instead
#         # raise HTTPException(status_code=401, detail="Invalid blockchain credentials")
#     except Exception as e:
#         logger.error(f"Authentication error: {str(e)}")
        
#         # PRODUCTION TESTING: Accept anyway for testing
#         logger.warning("PRODUCTION TESTING: Accepting despite error")
#         return credentials
        
#         # REAL PRODUCTION: Use this instead
#         # raise HTTPException(status_code=401, detail=f"Authentication error: {str(e)}")

# async def deduct_cv_credit(user_address: str, secure_token: str):
#     """Deducts a CV credit from the user's account"""
#     # Try using the contract service first
#     if contract_service_available:
#         try:
#             logger.info(f"Attempting to deduct credit using contract service for: {user_address}")
#             result = await xion_contract_service.deduct_cv_credit_with_retry(
#                 user_address, secure_token, max_retries=2
#             )
            
#             if result.get("success", False):
#                 logger.info(f"Successfully deducted credit: {result}")
#                 return result
            
#             logger.warning(f"Failed to deduct credit: {result}")
#         except Exception as e:
#             logger.error(f"Error deducting credit with contract service: {str(e)}")
    
#     # For production testing, return a mock response
#     logger.warning("PRODUCTION TESTING: Using mock credit deduction")
#     return {
#         "success": True,
#         "tx_hash": "mock_tx_hash_production_test",
#         "credits_remaining": 99
#     }

# Mock implementation for development remains the same
async def mock_verify_blockchain_credentials(
    x_user_address: str = Header(...),
    x_secure_token: str = Header(...)
) -> BlockchainCredentials:
    """Mock implementation for development"""
    logger.info("DEVELOPMENT MODE: Using mock blockchain verification")
    
    # Basic validation
    if not x_user_address.startswith("xion"):
        raise HTTPException(status_code=401, detail="Invalid wallet address format")
        
    if not x_secure_token or len(x_secure_token.split(":")) < 3:
        raise HTTPException(status_code=401, detail="Invalid token format")
    
    # Always accept in development mode
    return BlockchainCredentials(
        user_address=x_user_address,
        secure_token=x_secure_token
    )